#!/bin/bash
#PBS -P pq84
#PBS -q normalbw 
#PBS -N hmmIBD_geo
#PBS -j oe
#PBS -m ae
#PBS -l walltime=24:00:00,mem=40GB,ncpus=5
#PBS -l storage=gdata/pq84+scratch/pq84
#PBS -M jacob.westaway@menzies.edu.au

echo "---------------------------------------"
echo "PBS: Job identifier is $PBS_JOBID"
echo "PBS: Job name is $PBS_JOBNAME"

echo "---------------------------------------"
echo "Set working env"
cd /g/data/pq84/malaria/Pk_Malaysian_Population_Genetics/outputs/05_Analyses/hmmIBD_geo_clusters
export PATH=$PATH:/g/data/pq84/bin/hmmIBD/   
module load R/4.1.0 
export R_LIBS_USER="/g/data/pq84/R"

echo "---------------------------------------"
echo "Run hmmIBD on Mf"
hmmIBD -i /g/data/pq84/malaria/Pk_Malaysian_Population_Genetics/outputs/05_Analyses/hmmIBD/hmmIBD.tsv -b Mf_exclude.txt -o Pk_Mf

echo "---------------------------------------"
echo "Run hmmIBD on Mn"
hmmIBD -i /g/data/pq84/malaria/Pk_Malaysian_Population_Genetics/outputs/05_Analyses/hmmIBD/hmmIBD.tsv -b Mn_exclude.txt -o Pk_Mn

echo "---------------------------------------"
echo "Finished"