#!/bin/bash
#PBS -P pq84
#PBS -q normalbw
#PBS -N pkdhfr
#PBS -j oe
#PBS -m ae
#PBS -l walltime=48:00:00,mem=16GB,ncpus=2
#PBS -l storage=gdata/pq84+scratch/pq84
#PBS -M jacob.westaway@menzies.edu.au

echo "---------------------------------------"
echo "PBS: Job identifier is $PBS_JOBID"
echo "PBS: Job name is $PBS_JOBNAME"

echo "---------------------------------------"
echo "Define paths"
module load bcftools/1.12

echo "---------------------------------------"
echo "---------------------------------------"
echo 'Change to working directory and set env variables'
cd /g/data/pq84/malaria/Pk_Malaysian_Population_Genetics/outputs/05_Analyses/drug_resistance/pkdhfr

echo "---------------------------------------"
echo "---------------------------------------"
bcftools view -o full_compressed.vcf.gz /g/data/pq84/malaria/Pk_Malaysian_Population_Genetics/outputs/05_Analyses/PK_consensus_filtered_pass.vcf
bcftools view -o full_compressed_unfiltered.vcf.gz /g/data/pq84/malaria/Pk_Malaysian_Population_Genetics/outputs/04_Variant_calling/filtered/FILTERED_SNPs.vcf
bcftools index -t full_compressed.vcf.gz
bcftools index -t full_compressed_unfiltered.vcf.gz

echo "---------------------------------------"
echo "---------------------------------------"
bcftools filter -R filter.txt -o pkdhfr_filtered.vcf.gz full_compressed.vcf.gz
bcftools filter -R filter.txt -o pkdhfr_unfiltered.vcf.gz full_compressed_unfiltered.vcf.gz

echo "---------------------------------------"
echo "---------------------------------------"
echo "FINSIHED"