#!/bin/bash
#PBS -P pq84
#PBS -q normalbw
#PBS -N Variant_quality
#PBS -j oe
#PBS -m ae
#PBS -l walltime=1:00:00,mem=40GB,ncpus=10
#PBS -l storage=gdata/pq84+scratch/pq84
#PBS -M jacob.westaway@menzies.edu.au

echo "---------------------------------------"
echo "PBS: Job identifier is $PBS_JOBID"
echo "PBS: Job name is $PBS_JOBNAME"
echo "Pk pop gen in Malaysia"

echo "---------------------------------------"
echo "---------------------------------------"
echo 'Change to working directory and set env variables'
OUTDIR="/g/data/pq84/malaria/Pk_Malaysian_Population_Genetics/outputs/04_Variant_calling/filtered/quality/"
PICARD="/g/data/pq84/bin/picard/build/libs/picard.jar"
INDEXTDIR="/g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/data/ref_genomes/PKA1H1/fasta/strain_A1_H.1.Icor.fasta"
GATK="/g/data/pq84/bin/GenomeAnalysisTK-3.8-1-0/GenomeAnalysisTK.jar"
module load R/4.1.0 
export R_LIBS_USER="/g/data/pq84/R"

mkdir $OUTDIR
cd /g/data/pq84/malaria/Pk_Malaysian_Population_Genetics/outputs/04_Variant_calling/filtered/

echo "---------------------------------------"
echo 'Make diagnostic tables for Variants Scores - snps'

java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar $GATK \
    -T VariantsToTable \
    -R $INDEXTDIR \
    -V GVCFall_SNPs.vcf \
    -F CHROM -F POS -F QUAL -F QD -F DP -F MQ -F GQ -F MQRankSum -F FS -F ReadPosRankSum -F SOR \
    -o $OUTDIR/GVCFall_SNPs.table


echo "---------------------------------------"
echo 'Make diagnostic tables for Variants Scores - indels'

java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar $GATK \
    -T VariantsToTable \
    -R $INDEXTDIR \
    -V GVCFall_INDELs.vcf \
    -F CHROM -F POS -F QUAL -F QD -F DP -F MQ -F GQ -F MQRankSum -F FS -F ReadPosRankSum -F SOR \
    -o $OUTDIR/GVCFall_INDELs.table

echo "---------------------------------------"
echo 'Plot with R'

Rscript /g/data/pq84/malaria/Pk_Malaysian_Population_Genetics/scripts/05_Variant_filtering/Plot_quality_scores.R

echo "---------------------------------------"
echo 'Finished'