#!/bin/bash
#PBS -P pq84
#PBS -q normal 
#PBS -N estMOI
#PBS -j oe
#PBS -m ae
#PBS -l walltime=24:00:00,mem=80GB,ncpus=10
#PBS -l storage=gdata/pq84+scratch/pq84
#PBS -M jacob.westaway@menzies.edu.au

echo "---------------------------------------"
echo "PBS: Job identifier is $PBS_JOBID"
echo "PBS: Job name is $PBS_JOBNAME"

echo "---------------------------------------"
echo "Paths to required software & load modules"
module load bcftools/1.12
module load java/jdk-8.40
module load samtools/1.12 

echo "---------------------------------------"
echo "Environment variables"
cd /g/data/pq84/malaria/Pk_Malaysian_Population_Genetics/outputs/05_Analyses
GATK="/g/data/pq84/bin/GenomeAnalysisTK-3.8-1-0/GenomeAnalysisTK.jar" 
INDEXTDIR="/g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/data/ref_genomes/PKA1H1/fasta/strain_A1_H.1.Icor.fasta"
BAM="/g/data/pq84/malaria/Pk_Malaysian_Population_Genetics/outputs/03_Bam-pre/final_bam/"
VCF="/g/data/pq84/malaria/Pk_clusters/outputs/04_Variant_calling/gatk"
OUTDIR="/g/data/pq84/malaria/Pk_Malaysian_Population_Genetics/outputs/05_Analyses/estMOI"
mkdir $OUTDIR

echo "---------------------------------------"
echo "Subset consensus for variants the passed filters"

java -Djava.iodir=$PBS_JOBFS -Xms3200m -Xmx3600m -jar $GATK \
    -T SelectVariants \
    -R $FASTA/strain_A1_H.1.Icor.fasta \
    -V $VCF/FILTERED_SNPs.vcf  \
    --excludeFiltered \
    -o estMOI/PK_consensus_filtered_pass.vcf

echo "---------------------------------------"
echo "Split Consensus VCF up into individual samples"
cd estMOI

bcftools view PK_consensus_filtered_pass.vcf | sed -n '/#CHROM/,$p' | head -n 1 | tr '\t' '\n' |  sed -n '/ERR2214837/,$p' > sample_names.txt

bcftools view -s ERR2214837 PK_consensus_filtered_pass.vcf > ERR2214837_sample.vcf


echo "---------------------------------------"
echo "Run estMOI"
perl /g/data/pq84/bin/estMOI/estMOI_1.03 $BAM/ERR2214837.dupmarked.realigned.recal.bam ERR2214837_sample.vcf $INDEXTDIR --out=ERR2214837


echo "---------------------------------------"
echo "Finished"