#!/bin/bash
#PBS -P pq84
#PBS -q normalbw 
#PBS -N hmmIBD_using_subset_filters
#PBS -j oe
#PBS -m ae
#PBS -l walltime=24:00:00,mem=40GB,ncpus=5
#PBS -l storage=gdata/pq84+scratch/pq84
#PBS -M jacob.westaway@menzies.edu.au

echo "---------------------------------------"
echo "PBS: Job identifier is $PBS_JOBID"
echo "PBS: Job name is $PBS_JOBNAME"

echo "---------------------------------------"
echo "Set working env"
export PATH=$PATH:/g/data/pq84/bin/hmmIBD/   
module load R/4.1.0 
export R_LIBS_USER="/g/data/pq84/R"
cd /g/data/pq84/malaria/Pk_Malaysian_Population_Genetics/outputs/05_Analyses/hmmIBD/subsets

echo "---------------------------------------"
echo "Create VCF tsv file for hmmIBD"
echo "---------------------------------------"
Rscript /g/data/pq84/malaria/Pk_Malaysian_Population_Genetics/scripts/06_Analysis/hmmIBD_genotype_file_subset.R

echo "---------------------------------------"
echo "Run hmmIBD"
hmmIBD -i hmmIBD_subset.tsv -b /g/data/pq84/malaria/Pk_Malaysian_Population_Genetics/outputs/05_Analyses/hmmIBD/exclude.txt  -o Pk_subset

echo "---------------------------------------"
echo "Finished"