#!/bin/bash
#PBS -P pq84
#PBS -q normalbw
#PBS -N hmmIBD_geno
#PBS -j oe
#PBS -m ae
#PBS -l walltime=9:00:00,mem=40GB,ncpus=5
#PBS -l storage=gdata/pq84+scratch/pq84
#PBS -M jacob.westaway@menzies.edu.au

echo "---------------------------------------"
echo "PBS: Job identifier is $PBS_JOBID"
echo "PBS: Job name is $PBS_JOBNAME"

echo "---------------------------------------"
echo "Set working env"
module load bcftools/1.12
module load java/jdk-8.40 
module load R/4.1.0 
export R_LIBS_USER="/g/data/pq84/R"
export PATH=$PATH:/g/data/pq84/bin/plink2/
export PATH=$PATH:/g/data/pq84/bin/hmmIBD/   
cd /g/data/pq84/malaria/Pk_Malaysian_Population_Genetics/outputs/05_Analyses/hmmIBD/geno_test

echo "---------------------------------------"
echo "Use the above variant set for the genotype set"
Rscript /g/data/pq84/malaria/Pk_Malaysian_Population_Genetics/scripts/06_Analysis/hmmIBD_testing/hmmIBD_genotype_file_geno.R

echo "---------------------------------------"
echo "Run hmmIBD"
hmmIBD -i hmmIBD.tsv -b /g/data/pq84/malaria/Pk_Malaysian_Population_Genetics/outputs/05_Analyses/hmmIBD/exclude.txt -o Pk

echo "---------------------------------------"
echo " FINISHED"