#!/bin/bash
#PBS -P pq84
#PBS -q normalbw
#PBS -N hmmIBD_seg_snps
#PBS -j oe
#PBS -m ae
#PBS -l walltime=48:00:00,mem=80GB,ncpus=10
#PBS -l storage=gdata/pq84+scratch/pq84
#PBS -M jacob.westaway@menzies.edu.au

echo "---------------------------------------"
echo "PBS: Job identifier is $PBS_JOBID"
echo "PBS: Job name is $PBS_JOBNAME"

echo "---------------------------------------"
echo "Set working env"
module load R/4.1.0 
export R_LIBS_USER="/g/data/pq84/R"
cd /g/data/pq84/malaria/Pk_Malaysian_Population_Genetics/outputs/05_Analyses/hmmIBD/subsets/

echo "---------------------------------------"
echo "Identify segregating SNPs"
Rscript /g/data/pq84/malaria/Pk_Malaysian_Population_Genetics/scripts/06_Analysis/hmmIBD_testing/segregating_SNPs.R
Rscript /g/data/pq84/malaria/Pk_Malaysian_Population_Genetics/scripts/06_Analysis/hmmIBD_testing/segregating_SNPs_generic.R
Rscript /g/data/pq84/malaria/Pk_Malaysian_Population_Genetics/scripts/06_Analysis/hmmIBD_testing/segregating_SNPs_proportion.R

echo "---------------------------------------"
echo "FINISHED"