#!/bin/bash
#PBS -P pq84
#PBS -q normalbw
#PBS -N Depth_R_wrangle
#PBS -j oe
#PBS -m ae
#PBS -l walltime=12:00:00,mem=80GB,ncpus=10
#PBS -l storage=gdata/pq84+scratch/pq84
#PBS -M jacob.westaway@menzies.edu.au

echo "---------------------------------------"
echo "PBS: Job identifier is $PBS_JOBID"
echo "PBS: Job name is $PBS_JOBNAME"

echo "---------------------------------------"
echo "Define paths and load modules"
module load R/4.1.0 
export R_LIBS_USER="/g/data/pq84/R"
cd /g/data/pq84/malaria/Pk_Malaysian_Population_Genetics/outputs/05_Analyses/mapping

echo "---------------------------------------"
echo "Add header line to depth depth summary"
awk '{print $1}' depth_summary.depth | uniq > chromosome.txt
echo -e Contig"\n"Bases | cat - filenames.txt | sed 's/.sorted.bam//g' | tr '\n' '\t' | awk '{print $0}' - | cat - depth_summary.depth > depth_with_header.tsv

echo "---------------------------------------"
echo "Wrangle script"
Rscript /g/data/pq84/malaria/Pm/scripts/05_Analyses/mapping_quality/depth_wrangle.R

echo "---------------------------------------"
echo "FINSIHED"