#!/bin/bash
#PBS -P pq84
#PBS -q normalbw
#PBS -N Depth_R_plot
#PBS -j oe
#PBS -m ae
#PBS -l walltime=48:00:00,mem=128GB,ncpus=20
#PBS -l storage=gdata/pq84+scratch/pq84
#PBS -M jacob.westaway@menzies.edu.au

echo "---------------------------------------"
echo "PBS: Job identifier is $PBS_JOBID"
echo "PBS: Job name is $PBS_JOBNAME"

echo "---------------------------------------"
echo "Define paths and load modules"
module load R/4.1.0 
export R_LIBS_USER="/g/data/pq84/R"
cd /g/data/pq84/malaria/Pm/outputs/05_Analyses/Mapping

echo "---------------------------------------"
echo "Plot script"
Rscript /g/data/pq84/malaria/Pm/scripts/05_Analyses/mapping_quality/depth_plot.R

echo "---------------------------------------"
echo "FINSIHED"