#!/bin/bash
#PBS -P pq84
#PBS -q normalbw
#PBS -N Map_Qual
#PBS -j oe
#PBS -m ae
#PBS -l walltime=48:00:00,mem=80GB,ncpus=10
#PBS -l storage=gdata/pq84+scratch/pq84
#PBS -M jacob.westaway@menzies.edu.au

echo "---------------------------------------"
echo "PBS: Job identifier is $PBS_JOBID"
echo "PBS: Job name is $PBS_JOBNAME"

echo "---------------------------------------"
echo "Define paths and load modules"
echo "---------------------------------------"
module load bbmap/38.93
module load samtools/1.12  
module load sambamba/0.8.1 
module load java/jdk-8.40 
BED="/g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/data/ref_genomes/PKA1H1/strain_A1_H.1.Icor.fasta.bed"
OUTDIR="/g/data/pq84/malaria/Pk_Malaysian_Population_Genetics/outputs/05_Analyses/mapping"
mkdir $OUTDIR
INDIR="/g/data/pq84/malaria/Pk_Malaysian_Population_Genetics/outputs/02_Mapping/"
cd $INDIR

echo "---------------------------------------"
echo 'Sort bams'
echo "---------------------------------------"

for file in *.bam; do samtools index $file; done

echo "---------------------------------------"
echo 'Mapping Quality'
echo "---------------------------------------"
for i in *.bam
do
samtools view -h --threads 10 $i | pileup.sh in=stdin 2> $OUTDIR/${i%.bam}.mapstats
done 

echo "---------------------------------------"
echo "Aggregate bbmap outputs"
echo "---------------------------------------"
cd $OUTDIR
tail -n +1 *mapstats | grep '.mapstats\|Read\|Mapped\|Ref\|Percent\|Average\|Standard' | sed 's/:/,/' | sed 's/<==/,/' > mapstats_summary.csv

echo "---------------------------------------"
echo 'Read Depth'
echo "---------------------------------------"

echo "---------------------------------------"
echo 'Create file with list of filenames'
echo "---------------------------------------"
cd $INDIR
ls *sorted.bam > filenames.txt
cp filenames.txt $OUTDIR

echo "---------------------------------------"
echo 'Exectue samtools depth'
samtools depth -a -b $BED -f filenames.txt -o $OUTDIR/depth_summary.depth

echo "---------------------------------------"
echo 'Clean Up'
echo "---------------------------------------"
rm -f *.mapstats

echo "---------------------------------------------------------------------------------------------------------------------"
echo "FINISHED"
echo "---------------------------------------------------------------------------------------------------------------------"