#!/bin/bash
#PBS -P pq84
#PBS -q normalbw
#PBS -N IGV_prep
#PBS -j oe
#PBS -m ae
#PBS -l walltime=24:00:00,mem=50GB,ncpus=16
#PBS -l storage=gdata/pq84+scratch/pq84
#PBS -M jacob.westaway@menzies.edu.au


echo "---------------------------------------"
echo "PBS: Job identifier is $PBS_JOBID"
echo "PBS: Job name is $PBS_JOBNAME"

echo "---------------------------------------"
module load samtools/1.12  

cd /g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/sWGA_batch/outputs/02_Mapping

samtools sort MK010_DKDN220017453-1A_H7YMHDSX5_L4.bam > MK010_DKDN220017453-1A_H7YMHDSX5_L4_sorted.bam
samtools index MK010_DKDN220017453-1A_H7YMHDSX5_L4_sorted.bam 

samtools sort RK017_DKDN220017433-1A_H7YMHDSX5_L4.bam > RK017_DKDN220017433-1A_H7YMHDSX5_L4_sorted.bam
samtools index RK017_DKDN220017433-1A_H7YMHDSX5_L4_sorted.bam 

samtools sort NQE310_DKDN220017446-1A_H7YMHDSX5_L4.bam > NQE310_DKDN220017446-1A_H7YMHDSX5_L4_sorted.bam
samtools index NQE310_DKDN220017446-1A_H7YMHDSX5_L4_sorted.bam 

samtools sort PCM091_DKDN220017448-1A_H7YMHDSX5_L4.bam > PCM091_DKDN220017448-1A_H7YMHDSX5_L4_sorted.bam
samtools index PCM091_DKDN220017448-1A_H7YMHDSX5_L4_sorted.bam 

samtools sort NRU43_DKDN220017441-1A_H7YMHDSX5_L4.bam > NRU43_DKDN220017441-1A_H7YMHDSX5_L4_sorted.bam
samtools index NRU43_DKDN220017441-1A_H7YMHDSX5_L4_sorted.bam 

samtools sort NTW25_DKDN220017461-1A_H7YMHDSX5_L4.bam > NTW25_DKDN220017461-1A_H7YMHDSX5_L4_sorted.bam
samtools index NTW25_DKDN220017461-1A_H7YMHDSX5_L4_sorted.bam 

echo "---------------------------------------"
echo "Finished"
